### ISSUE TITLE
Metro Bundler for imgix-url-builder has encountered an errror

### ISSUE THREAD

**Issue by morio921** [prismicio-community/imgix-url-builder#2]
After installing the @prismicio/client and @prismicio/react packages on my react-native codebase, imgix-url-builder was also installed since it is one of the dependency of @prismicio.

But I'm getting the error when running the app.

error: bundling failed: Error: While trying to resolve module `imgix-url-builder` from file `/.../node_modules/@prismicio/helpers/dist/index.js`, the package `/.../node_modules/imgix-url-builder/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/.../node_modules/imgix-url-builder/dist/index.cjs`. Indeed, none of these files exist:

  * /.../node_modules/imgix-url-builder/dist/index.cjs(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * /.../node_modules/imgix-url-builder/dist/index.cjs/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)

**Comment by angeloashmore** [comment]
Hey @morio921, thanks for the report, and apologies for the delay.

Could you update to the latest version of `imgix-url-builder`, `v0.0.3`? You should be able to run the following command to do so:

```sh
npm update imgix-url-builder
```

If that doesn't work, you may need to uninstall `@prismicio/client` and `@prismicio/react` and re-install since `imgix-url-builder` is a nested dependency of both.
